### ISSUE TITLE
can´t find plugin.toml and dokku_common

### ISSUE THREAD

**Issue by busla** [zarthross/dokku-neo4j#4]
Installing on Dokku 4 with: `$ sudo dokku plugin:install https://github.com/zarthross/dokku-neo4j` is successfull but when I run the `$ dokku` command I get this error:

```
2015/10/02 09:08:41 open /var/lib/dokku/plugins/available/dokku-neo4j/plugin.toml: no such file or directory
/var/lib/dokku/plugins/enabled/dokku-neo4j/vars: line 2: /var/lib/dokku/plugins/enabled/dokku-neo4j/../dokku_common: No such file or directory
```

**Comment by zarthross** [comment]
I apologize that the documentation does not make this very clear, but the plugin is intended for use with dokku-alt and has not been tested with standard dokku.

**Comment by zarthross** [comment]
0dab8efde44b7f57d0354d3a6854b9c8e05c2670 addresses this issue with the documentation.  When I get a chance I'll look into what it will take to support this plugin on the original dokku.
